### ISSUE TITLE
Provide interface based on resultsets

### ISSUE THREAD

**Issue by alexmbraga** [eubr-atmosphere/tma-framework-a#35]
Adapt privacy component to offer a public interface (API) for Java applications which uses a resultsets (see JDBC) instead of files. That is, when using this new interface, the component's output is a resultset. 
This adaptation would facilitate the addition of privacy controls (based upon k-anonymity) to java apps.

**Comment by mrmassis** [comment]
I'm studying JDBC.

**Comment by brenofranca83** [comment]
Hi all (@mrmassis @tbasso ),
Some additional info for this issue:

- The new interface to be provided for the anonymizer should address a ResultSet as a dataset.
So, I understand the new public method should be something like

public ResultSet run(ResultSet dataset, String policy, int k, float riskThreshold);

In this sense, we'll need to construct the Data object for arx as the method create in
https://github.com/arx-deidentifier/arx/blob/master/src/main/org/deidentifier/arx/Data.java

There are several arx examples and one of them should do something similar in
https://github.com/arx-deidentifier/arx/tree/master/src/example/org/deidentifier/arx/examples

Note the riskThreshold (rmax) is now out of the policy file as a matter of semantics/cohesion.
Besides, the policy file should be formated as a JSON file. So, please use the native Java JSON API:
http://www.oracle.com/technetwork/articles/java/json-1973242.html

The JSON format should follow the idea of the policy format, identifying non-sensitive fields, 
identifying/PKs/SKs fields, and anonymization mechanisms (SR, SL, DT, AG, CT).

**Comment by alexmbraga** [comment]
moving this to PRIVAaaS
