### ISSUE TITLE
[PRIVAaaS] Refactory of file hierarchy

### ISSUE THREAD

**Issue by alexmbraga** [eubr-atmosphere/tma-framework-a#40]
- A hierarchy of files is defined statically. It can be generalized to be dynamic like the privacy policy.
We need a (simple) design for this refactory. 
@tbasso please detail.

**Comment by tbasso** [comment]
According to our telco in july, 2th, it was decided that the hierarchy files will be used as input, as well as the anonymization policy, and must be loaded to the component. They must be separated files.

**Comment by tbasso** [comment]
Design was decided according to previous comment. 
The development is ongoing @mrmassis
